### PR TITLE
Allow to build with browserify

### PR DESCRIPTION
**Pull request by McOmghall**
This marks the main file to be included in browserify requires. Solves https://github.com/jcassee/angular-hypermedia/issues/24

### CODE REVIEW

**Comment by jcassee** [comment]
Hi, Pedro, this adds a duplicate `main` property to `package.json`. I had already added one that should work with a npm-based build process. Does the `dist/linkheader-parser-node.js` not work for browserify? Do you know why not?

**Comment by McOmghall** [comment]
I actually made a mistake here and the new line should read `"browser"` instead of `"main"`: corrected it in a new commit. The problem is the `node` build of this package doesn't expose a global `linkHeaderParser`. Same problem for `mediaTypeParser` in the `mediatype-parser` module. Didn't try to build for `node`, just for the browser though.

**Comment by jcassee** [comment]
Thanks, Pedro!

**Comment by jcassee** [comment]
Released as 0.1.2.

**Pull request merged**
